version: '3.8'

services:
  database:
    image: postgres:13.16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=consul_testing
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - database
    ports:
      - "3005:3000"
    volumes:
      - .:/var/www/consul
      - bundle:/usr/local/bundle
      - node_modules:/var/www/consul/node_modules
    environment:
      - RAILS_ENV=testing
      - RACK_ENV=testing
      - DB_HOST=database
      - PGUSER=postgres
      - PGPASSWORD=${PGPASSWORD-$POSTGRES_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@database:5432/consul_testing
    command: bundle exec puma -C config/puma/testing.rb

volumes:
  db_data:
  bundle:
  node_modules: 